# Generated by Django 3.1.6 on 2021-04-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210402_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclubuser',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
